name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip clang
        pip install conan

    - name: Set up compiler
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        
    - name: Install dependencies (Conan)
      run: |
        conan profile detect
        conan install . -of build --build=missing \
          -s compiler=clang \
          -s compiler.version=14 \
          -s compiler.libcxx=libstdc++20

       

    - name: Configure (CMake)
      run: cmake --preset conan-release

    - name: Build
      run: cmake --build --preset conan-release

    - name: Run tests
      run: ctest --preset conan-release --output-on-failure
